### PR TITLE
add support for babel 5.0’s error.codeFrame

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you describe what a `codeFrame` is?  Maybe an example of the output with this?

**Comment by stefanpenner** [comment]
> Can you describe what a codeFrame is? Maybe an example of the output with this?

@sebmck moved the code snippet of the source of the parse error out of the error + stack, it now just lives as .codeFrame

**Comment by joliss** [comment]
@rwjblue It's a file context, like [this screenshot](https://github.com/broccolijs/broccoli/issues/240#issuecomment-84077683).

I'm actually wondering though, is there ever a case where we can't auto-generate the complete code frame from file/line/col? Babel's code frame doesn't seem to provide any info we don't already have in file/line/col. So rather than adding redundant information to the error object, perhaps we can add auto-generated code frames to the error page, and see if that might already cover all of our use cases...

**Comment by stefanpenner** [comment]
> Babel's code frame doesn't seem to provide any info we don't already have in file/line/col. So rather than adding redundant information to the error object, perhaps we can add auto-generated code frames to the error page, and see if that might already cover all of our use cases...

I don't believe we currently have immediate access to the source babel choked on, so the line/col information will have to also rely on us threading the file content forward, or making the assumption that the path/file correlate to input file, and not some derived file.

At this point I don't really have the bandwidth to do the re-construction on our side.

**Comment by rwjblue** [comment]
Many transformations may have happened from the file we know on disk. So the file, line, column info doesn't seem useful directly.

**Comment by stefanpenner** [comment]
@joliss i can gladly append the codeFrame back to .message for the time being. Let me know.

**Comment by joliss** [comment]
> At this point I don't really have the bandwidth to do the re-construction on our side.

That's fine, we can do it later.

I'm a bit hesitant to add API until we're actually convinced that we need it. So for the Babel case, let's tack it onto `.message` for now like you said, Stef, and once Broccoli auto-generates the code frame we can take it out again.

**Comment by stefanpenner** [comment]
ember-cli 0.2.3 will see this in the stack.

**Pull request closed without merging**
