### PR TITLE
Manually exit process

### PR DESCRIPTION
**Pull request by asakusuma**
Partial revert of https://github.com/broccolijs/broccoli/pull/476
to work around https://github.com/babel/broccoli-babel-transpiler/issues/169

Kept the tests and ensuring the correct exit code is called, but put back the manual process exiting.

### CODE REVIEW

**Comment by asakusuma** [comment]
The one failing job seemed to hit an unrelated tooling error:
```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.2.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/broccoli/broccoli/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by rwjblue** [comment]
Re-ran CI (yarn install failed on macOS)

**Comment by stefanpenner** [comment]
This is a workaround, could an inline comment be added describing the rationale?

The proper solution is a little more involved, and requires adding a destructor concept to broccoli pipelines, and plugins.

**Comment by stefanpenner** [comment]
opened an issue: https://github.com/broccolijs/broccoli/issues/479

**Pull request merged**
