### PR TITLE
Add ability for external consumers of broccoli/middleware to inject a li...

### PR DESCRIPTION
**Pull request by stefanpenner**
...ve-reload script.

further context: https://github.com/ember-cli/ember-cli/pull/3673#issuecomment-86929617

### CODE REVIEW

**Comment by rwjblue** [comment]
AppVeyor doesn't seem to support node 0.10 any longer so it is failing that build (but AppVeyor did pass for node 0.12).

**Comment by stefanpenner** [comment]
@rwjblue the failure looks related to the github DOS though

**Comment by joliss** [comment]
AppVeyor is flickering at the moment; I'm not terribly worried :)

**Comment by joliss** [comment]
Released in 0.15.2 - thanks! :)

Out of curiosity, is there a reason why you're preferring `/*, options */` and `arguments[1]` over `options = options || {}`?

**Comment by stefanpenner** [comment]
> over options = options || {}?

* the jshint disallows this
* it also makes debugging somewhat painful

**Comment by joliss** [comment]
Ah - maybe I just haven't run into the debugging problems you've seen. JSHint passes fine though (as long as you don't put a `var`):

```diff
diff --git a/lib/middleware.js b/lib/middleware.js
index 75f63d7..ac982cc 100644
--- a/lib/middleware.js
+++ b/lib/middleware.js
@@ -8,8 +8,8 @@ var mime = require('mime')
 var errorTemplate = handlebars.compile(fs.readFileSync(path.resolve(__dirname, '../templates/error.html')).toString())
 var dirTemplate = handlebars.compile(fs.readFileSync(path.resolve(__dirname, '../templates/dir.html')).toString())

-module.exports = function(watcher/* , options */) {
-  var options =  arguments[1] || {};
+module.exports = function(watcher, options) {
+  options = options || {}

   return function broccoliMiddleware(request, response, next) {
     watcher.then(function(hash) {
```

**Pull request merged**
