### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by krisselden**

### CODE REVIEW

**Comment by joliss** [comment]
I don't want to maintain TypeScript definitions in parallel. So I wouldn't want to merge this unless I can actually use TypeScript as part of my development workflow for Broccoli (I haven't tried).

**Comment by krisselden** [comment]
@joliss I'm happy to maintain it and/or would you be open to using ts for broccoli?

**Comment by krisselden** [comment]
I'm happy to convert things, it would be helpful to have well defined interfaces.  I'm also happy to keep declarations in sync.

**Comment by rwjblue** [comment]
@krisselden - We should look at this again. If we want to publish types, we should just rewrite in typescript....

**Comment by oligriffiths** [comment]
@krisselden see https://github.com/broccolijs/broccoli/pull/390 ;)

**Comment by stefanpenner** [comment]
the project has been rewritten in typescript, i suspect we can close this now.

**Pull request closed without merging**
