### PR TITLE
Output port in use error if 2 servers started on the same port

### PR DESCRIPTION
**Pull request by oligriffiths**
This has always irritated me, when starting a server when you always have one running, and you get this nasty error:
image

So I made it nicer:
image

### CODE REVIEW

**Comment by oligriffiths** [comment]
@stefanpenner yeah for sure. TBH we should look to use this server in ember-cli

**Comment by rwjblue** [comment]
I think this is good (bad error messages suck), but we should make the default behavior the same as what ember-cli does with `ember s --port 0` (it finds an available port automatically for you).

**Comment by oligriffiths** [comment]
@rwjblue good idea, I think that should be a separate PR though

**Comment by stefanpenner** [comment]
Lgtm!

**Comment by stefanpenner** [comment]
The future pr may always want to default to port 0

**Pull request merged**
